import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        // Brand: emerald = growth. Kept as the primary accent.
        primary: {
          50: '#ecfdf5',
          100: '#d1fae5',
          200: '#a7f3d0',
          300: '#6ee7b7',
          400: '#34d399',
          500: '#10b981',
          600: '#059669',
          700: '#047857',
          800: '#065f46',
          900: '#064e3b',
        },
        // Neutral: slate (cooler, modern fintech). Same keys -> every gray-* class still resolves.
        gray: {
          50: '#f8fafc',
          100: '#f1f5f9',
          200: '#e2e8f0',
          300: '#cbd5e1',
          400: '#94a3b8',
          500: '#64748b',
          600: '#475569',
          700: '#334155',
          800: '#1e293b',
          900: '#0f172a',
        },
      },
      fontFamily: {
        // Inter for Latin; graceful CJK via system fonts (PingFang/YaHei/Noto).
        sans: [
          'var(--font-inter)',
          'system-ui',
          '-apple-system',
          '"Segoe UI"',
          'Roboto',
          '"PingFang SC"',
          '"Hiragino Sans GB"',
          '"Microsoft YaHei"',
          '"Noto Sans SC"',
          'sans-serif',
        ],
        // Monospace for ASCII diagrams + tabular numbers; Menlo/Consolas render box-drawing chars.
        mono: [
          'ui-monospace',
          'SFMono-Regular',
          'Menlo',
          'Monaco',
          'Consolas',
          '"Liberation Mono"',
          'monospace',
        ],
      },
      boxShadow: {
        card: '0 1px 2px 0 rgb(15 23 42 / 0.05)',
        'card-hover':
          '0 4px 16px -4px rgb(15 23 42 / 0.10), 0 2px 6px -2px rgb(15 23 42 / 0.05)',
        pop: '0 12px 32px -8px rgb(15 23 42 / 0.18)',
      },
      typography: {
        DEFAULT: {
          css: {
            maxWidth: 'none',
            color: '#334155',
            lineHeight: '1.75',
            p: { marginTop: '1.25em', marginBottom: '1.25em' },
            a: {
              color: '#059669',
              fontWeight: '500',
              textDecoration: 'none',
              borderBottom: '1px solid rgb(5 150 105 / 0.30)',
              transition: 'color .2s, border-color .2s',
            },
            'a:hover': { color: '#047857', borderBottomColor: '#047857' },
            strong: { color: '#0f172a', fontWeight: '600' },
            h1: {
              color: '#0f172a',
              fontWeight: '700',
              letterSpacing: '-0.02em',
              fontSize: '2.25em',
              marginTop: '0',
              marginBottom: '0.9em',
              lineHeight: '1.15',
            },
            h2: {
              color: '#0f172a',
              fontWeight: '600',
              letterSpacing: '-0.01em',
              fontSize: '1.5em',
              marginTop: '2.25em',
              marginBottom: '0.9em',
              lineHeight: '1.3',
              paddingBottom: '0.4em',
              borderBottom: '1px solid #e2e8f0',
            },
            h3: {
              color: '#0f172a',
              fontWeight: '600',
              fontSize: '1.25em',
              marginTop: '1.8em',
              marginBottom: '0.6em',
              lineHeight: '1.4',
            },
            h4: {
              color: '#0f172a',
              fontWeight: '600',
              fontSize: '1.05em',
              marginTop: '1.6em',
              marginBottom: '0.5em',
            },
            ul: { marginTop: '1.25em', marginBottom: '1.25em' },
            ol: { marginTop: '1.25em', marginBottom: '1.25em' },
            li: { marginTop: '0.5em', marginBottom: '0.5em' },
            'ul > li::marker': { color: '#94a3b8' },
            'ol > li::marker': { color: '#94a3b8', fontWeight: '500' },
            blockquote: {
              fontStyle: 'normal',
              fontWeight: '400',
              color: '#475569',
              borderLeftWidth: '0.25rem',
              borderLeftColor: '#10b981',
              backgroundColor: '#ecfdf5',
              padding: '0.75rem 1.25rem',
              borderRadius: '0 0.5rem 0.5rem 0',
              marginTop: '1.75em',
              marginBottom: '1.75em',
              quotes: 'none',
            },
            'blockquote p:first-of-type::before': { content: 'none' },
            'blockquote p:last-of-type::after': { content: 'none' },
            code: {
              color: '#0f172a',
              backgroundColor: '#f1f5f9',
              border: '1px solid #e2e8f0',
              borderRadius: '0.375rem',
              padding: '0.15em 0.4em',
              fontSize: '0.875em',
              fontWeight: '500',
            },
            'code::before': { content: 'none' },
            'code::after': { content: 'none' },
            pre: {
              color: '#0f172a',
              backgroundColor: '#f8fafc',
              border: '1px solid #e2e8f0',
              borderRadius: '0.75rem',
              padding: '1rem 1.25rem',
              overflowX: 'auto',
              fontSize: '0.8125em',
              lineHeight: '1.6',
              marginTop: '1.75em',
              marginBottom: '1.75em',
            },
            'pre code': {
              backgroundColor: 'transparent',
              border: 'none',
              padding: '0',
              fontSize: 'inherit',
              color: 'inherit',
              fontWeight: 'inherit',
            },
            hr: { borderColor: '#e2e8f0', marginTop: '3em', marginBottom: '3em' },
            img: { borderRadius: '0.75rem', marginTop: '2em', marginBottom: '2em' },
            figure: { marginTop: '2em', marginBottom: '2em' },
            figcaption: {
              color: '#64748b',
              fontSize: '0.875em',
              marginTop: '0.75em',
              textAlign: 'center',
            },
            table: { fontSize: '0.9em', lineHeight: '1.5' },
            thead: { borderBottomWidth: '1px', borderBottomColor: '#cbd5e1' },
            'thead th': { color: '#0f172a', fontWeight: '600' },
            'tbody tr': { borderBottomWidth: '1px', borderBottomColor: '#f1f5f9' },
            'tbody td': { color: '#334155' },
          },
        },
      },
    },
  },
  plugins: [require('@tailwindcss/typography')],
}
export default config
